common:
    lid_topic: "/points_lio"
    # imu_topic:  "/imu/data"
    #lid_topic:  "points_raw"
    imu_topic: "/imu_data"
    time_sync_en: ture # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 2 # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 16
    blind: 2

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 180
    det_range: 100.0
    # lidar->imu 变换矩阵
    extrinsic_T: [0.08704262, -0.11147986, 0.60000775] #   extrinsic_T: [ 0, 0, 0.28]
    extrinsic_R: [
            0.994486,
            -0.052957,
            0.090512,
            0.054145,
            0.998476,
            -0.010715,
            -0.089807,
            0.015557,
            0.99583884,
    ] #  extrinsic_R

publish:
    scan_publish_en: 1 # 'false' will close all the point cloud output
    dense_publish_en: 1 # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: 1 # output the point cloud scans in IMU-body-frame
